export { default as HomePage } from './home/HomePage'
export { default as Login } from './auth/login/Login'
export { default as Register } from './auth/register/Register'
export { default as NotFountPage } from './error/notFountPage/NotFountPage'
export { default as BookInfo } from './bookInfo/BookInfo'
export { default as CreateBook } from './createBook/CreateBook'
export { default as EditBook } from './EditBook/EditBook'
